AWSTemplateFormatVersion: "2010-09-09"

Description: ECS Runtime

Resources:

  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Backend ECS Service
      VpcId: vpc-03122a127ece44b0b

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8001
          ToPort: 8001
          CidrIp: 0.0.0.0/0