name: Docker CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    bra**hes:
      - main
      - develop** workflow_dispatch:

permissions:** contents: read

jobs:
  build-ba**end-image:
    name: Build backen**container
    runs-on: ubuntu-lat**t

    steps:
      - name: Check**ut repository
        uses: actio**/checkout@v7

      - name: Set u**Docker Buildx
        uses: docke**setup-buildx-action@v4

      - n**e: Build backend image
        us**: docker/build-push-action@v7
   **   with:
          context: ./bac**nd
          file: ./backend/Dock**file
          push: false
      **  tags: maths-jump-and-go-backend**i
          cache-from: type=gha
**        cache-to: type=gha,mode=m**
